---
title: med24
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: news-items
  values:
    heading:
    link:
    image:
- scope:
    path: ''
    type: programs
  values:
    name:
    short:
    icon:
    cta:
encoding: utf-8
version: v1
description: A collection of the assets we hold so dear.
favicon: assets/images/logo.svg
tv: 4.5.3
markdown: kramdown
exclude:
- node_modules
- gulpfile.js
jekyll_get:
  data: team
  json: https://18f.gsa.gov/hub/api/team/
# social:
# - name: Facebook
#   link: https://www.facebook.com/Bartlom%C3%A9-Soccer-Academy-1699026550336895/
# nav:
# - name: Programs
#   link: "/#programs"
# - name: About
#   drop:
#   - name:
#     link: "/#about-"
#   - name: Staff
#     link: "/#about-staff"
# - name: Contact
#   link: "/#contact"
